name: Block external PRs to main
on:
  pull_request_target:
    branches: [ "main" ]
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  close-pr:
    if: >
      github.event.pull_request.author_association != 'OWNER' &&
      github.event.pull_request.author_association != 'MEMBER' &&
      github.event.pull_request.author_association != 'COLLABORATOR'
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Afficher le statut
        run: echo "Le statut de l'auteur de cette PR est ${{ github.event.pull_request.author_association }}"

      - name: Close the PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**Alert:** Only team members can open a Pull Request to `main`. If you wish to contribute, please target the `dev` branch.'
            })
            github.rest.pulls.update({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })